# Copyright 2023 Autodesk, Inc.  All rights reserved.
#
# Use of this software is subject to the terms of the Autodesk license agreement
# provided at the time of installation or download, or which otherwise accompanies
# this software in either electronic or hard copy form.

jobs:

- job: Install Source Dependencies
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: template.yml
    parameters:
      python_version: 3.9
  - script: |
      python update_requirements.py
      ./install_source_only.sh
      git commit -am "Update source requirements"
      git push
    displayName: Run Scripts
    workingDirectory: resources/python

- job: Install Binary Dependencies Linux 3.7
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: template.yml
    parameters:
      python_version: 3.7
  - script: |
      ./install_binary_linux.sh
      git commit -am "Update binary requirements in Linux Python 3.7"
      git push
    displayName: Run Scripts
    workingDirectory: resources/python

- job: Install Binary Dependencies Linux 3.9
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: template.yml
    parameters:
      python_version: 3.9
  - script: |
      ./install_binary_linux.sh
      git commit -am "Update binary requirements in Linux Python 3.9"
      git push
    displayName: Run Scripts
    workingDirectory: resources/python

- job: Install Binary Dependencies Mac 3.7
  pool:
    vmImage: 'macOS-12'
  steps:
  - template: template.yml
    parameters:
      python_version: 3.7
  - script: |
      ./install_binary_mac.sh
      git commit -am "Update binary requirements in Mac Python 3.7"
      git push
    displayName: Run Scripts
    workingDirectory: resources/python

- job: Install Binary Dependencies Mac 3.9
  pool:
    vmImage: 'macOS-12'
  steps:
  - template: template.yml
    parameters:
      python_version: 3.9
  - script: |
      ./install_binary_mac.sh
      git commit -am "Update binary requirements in Mac Python 3.9"
      git push
    displayName: Run Scripts
    workingDirectory: resources/python

- job: Install Binary Dependencies Windows 3.7
  pool:
    vmImage: 'windows-2022'
  steps:
  - template: template.yml
    parameters:
      python_version: 3.7
  - script: |
      .\install_binary_windows.ps1
      git commit -am "Update binary requirements in Windows Python 3.7"
      git push
    displayName: Run Scripts
    workingDirectory: resources/python

- job: Install Binary Dependencies Windows 3.9
  pool:
    vmImage: 'windows-2022'
  steps:
  - template: template.yml
    parameters:
      python_version: 3.9
  - script: |
      .\install_binary_windows.ps1
      git commit -am "Update binary requirements in Windows Python 3.9"
      git push
    displayName: Run Scripts
    workingDirectory: resources/python